### ISSUE TITLE
Fix alignment of options

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-google-maps#643] opened 2018-06-05 11:59 UTC
![image](https://user-images.githubusercontent.com/16645118/40974721-aa0d6630-68c8-11e8-9a49-467d09a775db.png)

**Comment by PerryRylance** [comment] 2018-07-11 11:16
Caused by whitespace, fixed by tidying up HTML

**Closed** 2018-07-11 11:17 UTC
Labels: bug
