### ISSUE TITLE
HTML Validation Issues

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-google-maps#159] opened 2016-10-05 07:42 UTC
https://validator.w3.org/nu/?showsource=yes&doc=http%3A%2F%2Fpayo-themes.com%2Fwp_tango%2F#l2360c12

**Comment by PerryRylance** [comment] 2019-11-29 14:24
Duplicate of #88

**Closed by PerryRylance** 2019-11-29 14:24 UTC
